name: Astronomer CI - Deploy code

on:
  workflow_dispatch:
    inputs:
      apiToken:
        description: "Astro API Token"
        required: true
        type: string


env:
  ASTRO_API_TOKEN: ${{ inputs.apiToken || secrets.ASTRO_API_TOKEN }}
  DEPLOYMENT_ID: "clu46gjat071c01ml9nnni5r5"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Astro
      uses: astronomer/deploy-action@v0.2
